services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always


  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network1

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      - network1



networks:
  network1:
    driver: bridge

volumes:
  mysql_data: {}
